enum Commands {
  HELP = "help",
  LS = "ls",
  CLEAR = "clear",
  ABOUT_ME = "about_me",
  CV = "cv",
  YOUTUBE = "youtube",
  GITHUB = "github",
  LEETCODE = "leetcode",
  CODEFORCES = "codeforces",
  TOPCODER = "topcoder",
  TWITTER = "twitter",
  COWSAY = "cowsay",
  SOCIALS = "socials",
  MAIL = "mail",
  BLOG = "blog",
  REGISTER = "register",
  LOGIN = "login",
  LOGOUT = "logout",
  MESSAGE = "message",
  WHOAMI = "whoami",
  SET_KEY = "set_key",
}

export default Commands;
